# Generated by Django 5.1.4 on 2024-12-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_alter_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.IntegerField(),
        ),
    ]
