# Generated by Django 5.1.4 on 2024-12-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
