# Generated by Django 5.1.4 on 2025-01-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('time_spent', models.CharField(max_length=8)),
            ],
        ),
    ]
