# Generated by Django 5.1.4 on 2025-01-14 07:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_studyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
